project_id = "sdrawnxfhiyyiiswqvni"

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.analyze-grant-guidelines]
verify_jwt = false

[functions.generate-report]
verify_jwt = false

[functions.cancel-report-run]
verify_jwt = false

[functions.resume-report-run]
verify_jwt = false

[functions.send-report-email]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = false